### ISSUE TITLE
 CurrentSimulationReport.log file

### ISSUE THREAD

**Issue by ghost** [tamnva/SWATShiny#57]
Con not find CurrentSimulationReport.log file in the Output folder. There is an error:
`Listening on http://127.0.0.1:7554
[SPS-ERROR] 2023-09-15 11:04:32 task 1 failed - "NA/NaN argument"`

Please help solve this problems.

**Comment by tamnva** [comment]
sorry for my late reply. Do you still face that issue now? if not I will close this issue
